### ISSUE TITLE
Add webcam function

### ISSUE THREAD

**Issue by aperoap1** [Jeredian/mks-wifi-plugin#167]
That would be great if you could integrate webcam With a link like "http://ip/webcam/?action=stream"
Thanks and regards
Juri

**Comment by ZombiKain** [comment]
And it would be great if you could integrate a webcam via the USB. 
For example, I have a Logitech C920 connected to my computer and I have to monitor printing through OBS Studio. It would be convenient if the camera would be displayed in the "MONITOR" tab in Cura.

**Comment by Jeredian** [comment]
@aperoap1 , @Nexurion both ideas look great, but this feature is planned for a quite long-time in the future, I can't say right now when we will start to work on it. Most of our users for this feature changing to the OctoPrint, because it has more flexibility for it and also has an extra environment outside of the Cura.

**Comment by ZombiKain** [comment]
@Jeredian, thanks for the answer! I will follow the updates and wait for the appearance of this feature. I still have little experience in 3D printing and the functionality of my printer is enough for me, so I don't want to changing to OctoPrint. Good luck to you in development and in life! :)
