### ISSUE TITLE
Add pip3 install libs to README

### ISSUE THREAD

**Issue by aldiserg** [Jeredian/mks-wifi-plugin#204]
### Is your feature request related to a problem?

Linux users can install it if doesnt work by default

### Describe the solution you'd like

pip3 install zeroconf ....

### Describe alternatives you've considered

now its not a easy to find how to solve problem with plugin integration

### Affected users and/or printers

Linux users

**Comment by Jeredian** [comment]
This idea is not fully related to our plugin, because we plugin not installs by itself any king of packages, and if you correctly check the `cura.log` file you will find that other plugins will have errors about `zeroconf` too. So it's more for Cura documentation. 
Maybe you need to check Cura documentation for it:

https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-Ubuntu
https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-openSUSE
