### ISSUE TITLE
 Problem With Cura MKS windows 11 Flying Bear Ghost 5

### ISSUE THREAD

**Issue by Kite79** [Jeredian/mks-wifi-plugin#275]
### Plugin Version

1.3.1

### Cura Version

4.13.1

### Platform

Windows 11

### Printer

Flying Bear Ghost 5

### Reproduction steps

Flying Bear Ghost 5 with Ultimaker Cura 4.13.1 with Plugin versione 1.3.1 or versione 1.3.0 and Windows 11 it does not work,
MKS can't connect with the printer...

Flying Bear Ghost 5 with Ultimaker Cura 4.13.1 with Plugin versione 1.3.1 or versione 1.3.0 and Windows 10 work.
MKS can connect with printer ...

### Actual results

i can connect only with old pc with windows 10

### Expected results

I don't know what to try to do

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8044349/cura.log)

**Comment by Jeredian** [comment]
Hi @snow79, 
to be sure that the issue is related to the windows 11 operation system you need to check several steps:
1. Flying bear supports only one active connection. So please turn off other instances of Cura.
2. If you are migrating from the 1.2.6 version. please make this workaround: turn off Wifi settings, restart Cura, add printer Ip address again, and then press the "Connect" button.
3. Turn off the antivirus, because sometimes it blocks Cura socket to any kind of printer in the local network

If after this check issue still be reproducible, let us know. we will try to investigate it asap.
