### ISSUE TITLE
Button "Delete" is not work, files from SD card cannot be removed remotely 

### ISSUE THREAD

**Issue by WEREWOLF1973** [Jeredian/mks-wifi-plugin#286]
### Plugin Version

1.3.3

### Cura Version

4.13.1

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Try all plugin releases 

### Actual results

All plugin releases have issue with inactive button "Delete file" in SD card menu

### Expected results

Possibility deleting files from SD card from plugin menu

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Menu](https://user-images.githubusercontent.com/38240586/164872904-888b80cd-3f4d-4f4b-998a-977e2286afb9.JPG)

**Comment by ParkerK** [comment]
@WEREWOLF1973 can you add a log file?

**Comment by WEREWOLF1973** [comment]
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8717198/cura.log)
Done

**Comment by ParkerK** [comment]
It _might_ be due to the reconnect/connect and disconnect loop bug https://github.com/Jeredian/mks-wifi-plugin/issues/289

Your logs show a constant attempt to reconnect, and if Cura is disconnected it may not allow you to delete (since it thinks the connection is broken).

You can either wait for an update, or you could try editing this file https://github.com/Jeredian/mks-wifi-plugin/pull/290/files

It will be in `C:\Users\YOURUSERNAME\AppData\Roaming\cura\4.13\Plugins\MKSWifiPlugin\MKSWifiPlugin\MKSOutputDevice.py`

**Comment by WEREWOLF1973** [comment]
> It _might_ be due to the reconnect/connect and disconnect loop bug #289
> 
> Your logs show a constant attempt to reconnect, and if Cura is disconnected it may not allow you to delete (since it thinks the connection is broken).
> 
> You can either wait for an update, or you could try editing this file https://github.com/Jeredian/mks-wifi-plugin/pull/290/files
> 
> It will be in `C:\Users\YOURUSERNAME\AppData\Roaming\cura\4.13\Plugins\MKSWifiPlugin\MKSWifiPlugin\MKSOutputDevice.py`

Done, but no effect....

**Comment by WEREWOLF1973** [comment]
No any progress till now
