### ISSUE TITLE
Continuous connection and disconnection to WiFi

### ISSUE THREAD

**Issue by Fulvio1** [Jeredian/mks-wifi-plugin#316]
### Plugin Version

1.4

### Cura Version

5.0

### Platform

Windows 10

### Printer

Flsun Q5

### Reproduction steps

Installing new version of MKS WiFi for Cura 5.00 from the market.
Reboot Cura

### Actual results

The connection is not stable. It connects and disconnects all the time making it impossible to use!

### Expected results

A stable connection with the printer!

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8844716/cura.log)
![screenshot 105](https://user-images.githubusercontent.com/106970804/172168287-f2f82a64-4791-40c4-a348-a611fadec242.jpg)

**Comment by Kite79** [comment]
Same problem:
Plugin Version
1.4

Cura Version
5.0

Platform
Windows 10

Printer
Flying bear Ghost 5  \\ Board Mks mini nano v3.1


Reproduction steps
Installing new version of MKS WiFi for Cura 5.00 from the market.
Reboot Cura

Actual results
The connection is not stable. It connects and disconnects all the time making it impossible to use!

Expected results
A stable connection with the printer!

- [x] Cura log file 
- [x] Screenshot  
[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8845840/cura.log)
![Desktop Screenshot 2022 06 06 - 18 03 02 58](https://user-images.githubusercontent.com/6748639/172201154-4cc6975b-a7b9-4021-8547-9264f51b0398.png)

**Comment by FlyDrag** [comment]
I discovered the same issue. This is not 100% reproducible, sometimes the plugin works fine. I have a deep network experience, so I made some simple troubleshooting of this issue.

1. I stopped cura and checked is the MKS WIFI firmware on my printer works as expected. I configured a proper session in putty and checked printer connection:
![изображение](https://user-images.githubusercontent.com/6630905/172228523-dd14f177-5ecb-4745-8e7e-5117668e2cd4.png)
Printer responds to my commands, so I can assume that firmware works fine:
![изображение](https://user-images.githubusercontent.com/6630905/172228876-885fddc0-9648-4545-bd21-af85493247a9.png)

2. I started my wireshark to check packets between my laptop and printer.

3. After that I closed the putty session (because MKS WIFI does support only 1 connection). I can see that the connection with printer was closed:
![изображение](https://user-images.githubusercontent.com/6630905/172229328-aaf06436-4306-4f73-a1b2-f86bd113af48.png)

4. I started cura with MKS WIFI plugin enabled and I can see that the tcp connection from MKS WIFI plugin to printer is reconnecting continiously.

6. In dump we can see that plugin starts 2 tcp connections to printer at the same time. And the printer drops the second  connection (as expected). 
![изображение](https://user-images.githubusercontent.com/6630905/172231042-7f43b165-a12d-4102-b8a5-1a92ffbf572b.png)

7. Plugin keeps the first connection for a long time and send some commands on it:
![изображение](https://user-images.githubusercontent.com/6630905/172231445-a9efc9c9-043c-4158-85c8-5b2ba09b32ec.png)

and gets a reply from printer
![изображение](https://user-images.githubusercontent.com/6630905/172231550-4912aa20-e820-45d2-b0a5-1e6f7019a983.png)

I found only one workaround for this problem - reset WIFI on router when cura is running. This helps because my laptop is on wire ethernet interface and doesn't loose connectivity when I reset wifi (so the tcp connection was reset on printer but is active in plugin), so second connection from plugin to printer works fine. After some time the plugin would reset stallen first connection. This workaround would not help if printer and PC would be connected to the same WiFI hotspot.

**Comment by laurent7878** [comment]
same issue too. When i uninstall plugin and add beta version it works again.

**Comment by Elkin-Vasily** [comment]
@FlyDrag thanks for your research it helped a lot.

Try to use version from this branch: https://github.com/Jeredian/mks-wifi-plugin/tree/issue-316

I cannot reproduce this bug on my setup, so i need some help with testing.

**Comment by FlyDrag** [comment]
@Elkin-Vasily I checked this branch. It seems that this issue was fixed.
I'll keep running issue-316 branch for some time.
